language: node_js

node_js:
  - "5"

notifications:
    slack:
      rooms:
        - anzumana: "AmoYKjOF7aQ7DKZDCyMTrvqc#open-aquarium"
      on_failure: always
      on_success: never

script: cd node_js && npm install && npm test
