language: node_js

node_js:
  - "5"

notifications:
  slack:
    rooms:
      - anzumana:AmoYKjOF7aQ7DKZDCyMTrvqc#open-aquarium
    on_success: never # default: always
    on_failure: always # default: always
script: cd node_js && npm install && npm test
